name: Build & Deploy with Jib

on:
  push:
    branches: ["main"]

jobs:
  build-bookmark-api:
    name: Build and Push bookmark-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./book-marker-backend/bookmark-api

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Authenticate Docker Hub for Jib
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          ./mvnw compile jib:build \
            -DskipTests \
            -Djib.to.image=${{ secrets.DOCKER_USERNAME }}/bookmark-api:latest \
            -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} \
            -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
